### ISSUE TITLE
.update() uses "wrong" HTTP method

### ISSUE THREAD

**Issue by originell** [crudlio/crudl-connectors-drf#1]
Doing a call to `.update()` does a `PATCH`. However, [the DRF docs specify](http://www.django-rest-framework.org/api-guide/routers/#defaultrouter) `PUT` for `update` and `PATCH` for `partial_update`.

**Comment by sehmaschine** [comment]
Thanks! Good point.

**Comment by vam** [comment]
In connectors' terminology an update is always a partial update. So PATCH is correct. If you need to use PUT for update, you can configure the crudl2http middleware.

**Comment by originell** [comment]
but wouldn't it make more sense to let the drf-connector reflect the DRF naming?

**Comment by vam** [comment]
I don't think so. The DRF implementation of connectors is a special case.

**Comment by originell** [comment]
I'll happily write my own crud2http middleware that handles this. I just think it's an unhappy coincidence that when I write a ViewSet:

```python
class MyViewSet(viewsets.ViewSet):
    def update(self, request, pk):
        # …
        return Response(data)
```

I can't use

```javascript
myConnector.update({…})
```

The terminology mismatch was really confusing. I thought it would be cool to have this named the same way so you save some mental capacity ;-)

Would it be possible to at least include a small note in the README? I could imagine that this will confuse more people than just me.

**Comment by sehmaschine** [comment]
I do agree that the naming confusion is unfortunate. However, the connector is independent of the API framework. A note within README should be fine IMO.

**Comment by vam** [comment]
PLUS: You can do this:
```js
const myOptions = {
  crudToHttp: { create: 'post', read: 'get', update: 'put', delete: 'delete' },
}
const myConnector = createDRFConnector(url, myOptions)
```

The crudToHttp middleware is part of the connectors-base package

**Comment by originell** [comment]
If that is the way to fix this, then why not make that the default way in `crudl-connectors-drf`? As it affects everyone using the django rest framework and this package is only meant to be used with drf anyway

**Comment by vam** [comment]
What is the most common way to update a resource with DRF? update or update_partial?

**Comment by originell** [comment]
Mh...

If we assume that most people try to use [`ModelViewSet`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/viewsets.py), which generates the backend handling on it's own, then we end up using the [`UpdateModelMixin`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/mixins.py#L61). As you can see the code for `update` and `partial_update` is basically the same. Except for the fact that, internally, `partial=True` is passed on to the used `serializer` when `partial_update` is called.

The usecase for `partial=True` is actually [a pretty important one](http://www.django-rest-framework.org/api-guide/serializers/#partial-updates):

> By default, serializers must be passed values for all required fields or they will raise validation errors. You can use the partial argument in order to allow partial updates.

So by calling `connector.update`, we actually trigger a `partial_update`. That's what I didn't expect. Now that I've read the docs, I even think that it's pretty dangerous that those terms get mixed up as they trigger a completely different backend validation behaviour.
